# FROM: node:21-alpine3.17

# COPY . /. 
FROM ubuntu
RUN apt-get update \
    && apt-get upgrade -y
WORKDIR /
COPY package*.json ./
COPY cypress /cypress
RUN apt-get update
RUN apt-get -y install curl
# RUN curl -sL https://deb.nodesource.com/setup_18.x  | bash -
# RUN apt-get -y install nodejs
# RUN npm install


