# e2e/docker-compose.yml from repo
# https://github.com/bahmutov/cypress-open-from-docker-compose
version: "3.2"
name: "test-cypress"

networks:
  another_network:
    driver: bridge

services:
  # Cypress container
  cypress:
    # the Docker image to use from https://github.com/cypress-io/cypress-docker-images
    image: "cypress/included:3.2.0"
    command: npx run cypress-test
    environment:
      # pass base url to test pointing at the web application
      - CYPRESS_baseUrl=http://sentimentalyzer:8123
    # share the current folder as volume to avoid copying
    #working_dir: /cypress/e2e
    volumes:
      - ./cypress:/e2e
      # - ./e2e/cypress:/app/cypress
      # - ./e2e/cypress.config.js:/app/cypress.config.js
