name: Manually test - cypress test

on: push
jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version}}
      - name: npm install
        run: npm ci
      - name: gui testing
        run:  npm run sezo #change nape depending on the folder?? 